// src/utils/iconMap.js


import {
    FaWifi,
    FaBath,
    FaTv,
    FaUmbrellaBeach,
    FaTshirt,
    FaFilm,
    FaChair,
    FaSmoking,
    FaStore,
    FaCoffee,
    FaSnowflake,
    FaFire,
    FaGlassMartini,
    FaWind,
    FaLock,
    FaCouch,
    FaUtensils,
    FaConciergeBell,
    FaPaw,
    FaWheelchair,
    FaBan,
    FaVolumeMute,
    FaToilet,
    FaShower,
    FaHotTub,
    FaSpa,
    FaDumbbell,
    FaSwimmingPool,
    FaParking,
    FaChargingStation,
    FaBriefcase,
    FaUsers,
    FaGlassCheers,
    FaChild,
    FaCocktail,
    FaTree,
    FaBuilding,
    FaMicrophone,
    FaGamepad,
    FaGolfBall,
    FaClock,
    FaSuitcase,
    FaBus,
    FaCar,
    FaMap,
    FaMoneyBillWave,
    FaSoap,
    FaDoorOpen,
    FaDesktop,
    FaMoneyCheck,
  } from 'react-icons/fa';
  
  const iconMap = {
    FaWifi: FaWifi,
    FaBath: FaBath,
    FaTv: FaTv,
    FaUmbrellaBeach: FaUmbrellaBeach,
    FaTshirt: FaTshirt,
    FaFilm: FaFilm,
    FaChair: FaChair,
    FaSmoking: FaSmoking,
    FaStore: FaStore,
    FaCoffee: FaCoffee,
    FaSnowflake: FaSnowflake,
    FaFire: FaFire,
    FaGlassMartini: FaGlassMartini,
    FaWind: FaWind,
    FaLock: FaLock,
    FaCouch: FaCouch,
    FaUtensils: FaUtensils,
    FaConciergeBell: FaConciergeBell,
    FaPaw: FaPaw,
    FaWheelchair: FaWheelchair,
    FaBan: FaBan,
    FaVolumeMute: FaVolumeMute,
    FaToilet: FaToilet,
    FaShower: FaShower,
    FaHotTub: FaHotTub,
    FaSpa: FaSpa,
    FaDumbbell: FaDumbbell,
    FaSwimmingPool: FaSwimmingPool,
    FaParking: FaParking,
    FaChargingStation: FaChargingStation,
    FaBriefcase: FaBriefcase,
    FaUsers: FaUsers,
    FaGlassCheers: FaGlassCheers,
    FaChild: FaChild,
    FaCocktail: FaCocktail,
    FaTree: FaTree,
    FaBuilding: FaBuilding,
    FaMicrophone: FaMicrophone,
    FaGamepad: FaGamepad,
    FaGolfBall: FaGolfBall,
    FaClock: FaClock,
    FaSuitcase: FaSuitcase,
    FaBus: FaBus,
    FaCar: FaCar,
    FaMap: FaMap,
    FaMoneyBillWave: FaMoneyBillWave,
    FaSoap: FaSoap,
    FaDoorOpen: FaDoorOpen,
    FaDesktop: FaDesktop,
    FaMoneyCheck: FaMoneyCheck,
  };
  
  export default iconMap;