name: Deploy Danjam Frontend to Lightsail

on:
  push:
    branches: [main]

concurrency:
  group: deploy-danjam
  cancel-in-progress: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: https://staysync.org
          NODE_ENV: production

      - name: Clean up /var/www/danjam
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.38.232.169    # 실제 서버 IP로 변경
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/danjam/*
            sudo mkdir -p /var/www/danjam
            sudo chown bitnami:bitnami /var/www/danjam
            sudo chmod u+w /var/www/danjam

      - name: Copy build files to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 3.38.232.169    # 실제 서버 IP로 변경
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build/*'
          target: '/var/www/danjam'
          strip_components: 1
          overwrite: true

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.38.232.169    # 실제 서버 IP로 변경
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl restart nginx

      - name: Test frontend deployment
        run: |
          curl -f https://danjam.in || exit 1
