# .github/workflows/main.yml
name: Deploy DanJam-In to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: https://staysync.org
          NODE_ENV: production

      - name: Verify build contains production API URL
        run: |
          echo "🔍 Checking for staysync.org in build artifacts…"
          grep -R "staysync.org" build/ || (echo "❌ staysync.org not found!" && exit 1)

      - name: Create 404.html for SPA routing
        run: |
          cp build/index.html build/404.html
          echo "<base href='/' />" >> build/404.html

      - name: Create CNAME file
        run: echo "danjam.in" > build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: danjam.in
